# -*- coding: utf-8 -*-
"""
patch_page.py — Evidence-First Architecture rewrite for page.tsx
Run from: d:/Sanjay/B.Tech CSE/nextup/frontend/
  $env:PYTHONIOENCODING="utf-8"; python patch_page.py
"""
import sys, re

FILE = "app/ai-toolkit/page.tsx"
with open(FILE, "r", encoding="utf-8", newline="") as f:
    src = f.read()

orig_len = len(src)
print(f"File loaded: {orig_len} chars")

# ─── helpers ─────────────────────────────────────────────────────────────────
def crlf(s):
    """Ensure consistent CRLF line endings."""
    return s.replace("\r\n", "\n").replace("\n", "\r\n")

def exact_replace(name, old, new, allow_multi=False):
    global src
    count = src.count(old)
    if count == 0:
        print(f"FAIL [{name}] — target not found!")
        sys.exit(1)
    if count > 1 and not allow_multi:
        print(f"WARN [{name}] — {count} occurrences, replacing first only")
    src = src.replace(old, new, 1)
    print(f"OK   [{name}]")

def regex_replace(name, pattern, new, flags=re.DOTALL):
    global src
    m = re.search(pattern, src, flags)
    if not m:
        print(f"FAIL [{name}] — regex not found!")
        sys.exit(1)
    src = src[:m.start()] + new + src[m.end():]
    print(f"OK   [{name}]")

# ═══════════════════════════════════════════════════════════════════════════════
# PATCH 1: Replace interfaces block (lines 67-138)
# Remove old: CopilotQuestion, VaultQA, Capability, AlignmentStrategy,
#             AlignmentResult, EvidenceNode, EvidenceGap, VerifiedEvidence
# Add new: WorkspaceCapability, UserEvidence, CapabilityCoverage,
#          EvidenceQuestion, ResumePatch, CapabilityVerification, VaultQA
# ═══════════════════════════════════════════════════════════════════════════════
OLD1 = crlf(
"""interface CopilotQuestion {
  id: string;
  type: "general" | "job_specific";
  stableKey: string;
  text: string;
  answer: string;
  sourceGapKey?: string;
  placeholder?: string;
}

interface VaultQA {
  stableKey?: string;
  question: string;
  answer: string;
  timestamp: string;
}

type Capability =
  | "backend_systems"
  | "real_time_systems"
  | "ml_systems"
  | "research_methodology"
  | "data_structures"
  | "networking"
  | "concurrency"
  | "deployment"
  | "observability";

type AlignmentStrategy =
  | "skill_verification"
  | "experience_enrichment"
  | "transferable_exploration"
  | "minimal_jd_targeting";

interface AlignmentResult {
  score: number;
  level: "High" | "Medium" | "Low";
  directOverlapCount: number;
  transferableOverlapCount: number;
  primaryStrategy: AlignmentStrategy;
}

interface EvidenceNode {
  id: string;
  type: "skill" | "project" | "experience" | "certification";
  name: string;
  confidence: number; // 0-100
  inferredCapabilities: Capability[];
  evidenceStrength: "strong" | "medium" | "weak";
  supportingEvidence: string[];
}

interface EvidenceGap {
  stableKey: string;
  category: "GENERAL" | "JOB_SPECIFIC";
  gapType: "missing_skill" | "weak_skill" | "project_depth" | "missing_metric" | "missing_infrastructure" | "enrichment_opportunity";
  skillOrProjectName: string;
  reason: string;
  evidenceMissing: string;
  importance: number; // 0-100
  confidence: number; // 0-100
  resumeImpactScore: number; // 0-100
  priority?: number;
}

interface VerifiedEvidence {
  stableKey: string;
  category: string;
  confidence: number;
  answer: string;
  usableForResume: boolean;
}""")

NEW1 = crlf(
"""// ─── Evidence-First Architecture Interfaces ───────────────────────────────────

/** A single JD capability, extracted by browser LLM + normalized to a canonical ID. */
interface WorkspaceCapability {
  id: string;               // canonical, e.g. "owasp_top_10"
  name: string;             // display name, e.g. "OWASP Top 10"
  importance: "critical" | "high" | "medium" | "low";
  category: string;         // e.g. "cybersecurity"
}

/** A piece of evidence extracted from resume or user vault. */
interface UserEvidence {
  capabilityId: string;
  text: string;             // e.g. "Built Flask backend with JWT auth"
  source: "resume" | "vault";
  verified: boolean;
}

/** 4-state evidence coverage for one capability. */
type EvidenceState = "strong" | "weak" | "unknown" | "missing";
interface CapabilityCoverage {
  capability: WorkspaceCapability;
  state: EvidenceState;
  matchedEvidence: UserEvidence[];
  reasoning: string;
}

/** A targeted question generated by browser LLM for one unknown/missing capability. */
interface EvidenceQuestion {
  id: string;
  capabilityId: string;
  capabilityName: string;
  text: string;
  answer: string;
  stableKey: string;
}

/** A patch operation on the resume JSON (not a full rewrite). */
interface ResumePatch {
  section: "skills" | "summary" | string;  // e.g. "project_0", "experience_1"
  action: "add" | "enhance" | "rephrase";
  content: string;
  reasoning: string;
}

/** Tracks which capabilities have been verified — prevents re-asking. */
interface CapabilityVerification {
  capabilityId: string;
  verified: boolean;
  source: "user_answer" | "resume" | "auto_detected";
  lastVerifiedAt: string;  // ISO date string
  evidenceSummary?: string;
}

/** Context vault entry (unchanged from existing schema for backwards compat). */
interface VaultQA {
  stableKey?: string;
  question: string;
  answer: string;
  timestamp: string;
}""")

exact_replace("1:interfaces", OLD1, NEW1)

# ═══════════════════════════════════════════════════════════════════════════════
# PATCH 2: Replace buildEvidenceGraph + buildFallbackGaps with
#          CAPABILITY_ONTOLOGY + 6-stage pipeline functions
# ═══════════════════════════════════════════════════════════════════════════════
# Old block starts at `function buildEvidenceGraph(` (line 357) and ends after
# `buildFallbackGaps` closing brace (line 749). Replace the whole block.
OLD2_START = "function buildEvidenceGraph(resumeData: any): EvidenceNode[] {"
OLD2_END   = "\r\nfunction parseRobustLLMJSON(rawText: string): any {"

# Find the exact substring from OLD2_START to OLD2_END (inclusive of start, exclusive of end-anchor)
pat2 = re.compile(
    re.escape(OLD2_START) + r".*?" + r"(?=" + re.escape(OLD2_END) + r")",
    re.DOTALL
)
m2 = pat2.search(src)
if not m2:
    print("FAIL [2:ontology-block] — anchor not found!")
    sys.exit(1)

NEW2 = crlf(
"""// ═══════════════════════════════════════════════════════════════════════════
// CAPABILITY ONTOLOGY — canonical IDs + aliases for normalization
// ═══════════════════════════════════════════════════════════════════════════

const CAPABILITY_ONTOLOGY: Record<string, {
  id: string; name: string; importance: "critical"|"high"|"medium"|"low"; category: string; aliases: string[];
}> = {
  // ─── Cybersecurity ────────────────────────────────────────────────────────
  owasp_top_10:           { id:"owasp_top_10",         name:"OWASP Top 10",              importance:"high",    category:"cybersecurity", aliases:["owasp","owasp top 10","owasp top ten","web vulnerabilities","sql injection","xss","csrf","broken auth"] },
  burp_suite:             { id:"burp_suite",            name:"Burp Suite",                importance:"high",    category:"cybersecurity", aliases:["burpsuite","burp","web proxy","intercepting proxy"] },
  nmap:                   { id:"nmap",                  name:"Nmap",                      importance:"medium",  category:"cybersecurity", aliases:["network mapper","network scanner","port scanner"] },
  metasploit:             { id:"metasploit",            name:"Metasploit",                importance:"medium",  category:"cybersecurity", aliases:["metasploit framework","msf"] },
  penetration_testing:    { id:"penetration_testing",   name:"Penetration Testing",       importance:"critical",category:"cybersecurity", aliases:["pentesting","pen testing","pen test","pentest","ethical hacking","vulnerability assessment"] },
  threat_modeling:        { id:"threat_modeling",       name:"Threat Modeling",           importance:"high",    category:"cybersecurity", aliases:["threat modelling","stride","attack surface"] },
  cloud_security:         { id:"cloud_security",        name:"Cloud Security",            importance:"high",    category:"cybersecurity", aliases:["cloud security posture","iam security","aws security","gcp security"] },
  api_security:           { id:"api_security",          name:"API Security",              importance:"high",    category:"cybersecurity", aliases:["api security testing","rest api security","broken object level"] },
  network_security:       { id:"network_security",      name:"Network Security",          importance:"medium",  category:"cybersecurity", aliases:["firewall","ids","ips","network monitoring","intrusion detection"] },
  ctf:                    { id:"ctf",                   name:"CTF Experience",            importance:"medium",  category:"cybersecurity", aliases:["capture the flag","hackthebox","tryhackme","picoctf","ctf competition","wargame"] },
  cryptography:           { id:"cryptography",          name:"Cryptography",              importance:"medium",  category:"cybersecurity", aliases:["encryption","aes","rsa","tls","ssl","hashing","pki"] },
  wireshark:              { id:"wireshark",             name:"Wireshark",                 importance:"low",     category:"cybersecurity", aliases:["packet analysis","packet capture","pcap"] },
  ssrf:                   { id:"ssrf",                  name:"SSRF",                      importance:"medium",  category:"cybersecurity", aliases:["server side request forgery","server-side request forgery"] },
  xss:                    { id:"xss",                   name:"XSS",                       importance:"medium",  category:"cybersecurity", aliases:["cross-site scripting","cross site scripting"] },
  sqli:                   { id:"sqli",                  name:"SQL Injection",             importance:"medium",  category:"cybersecurity", aliases:["sql injection","sqli","database injection"] },
  llm_security:           { id:"llm_security",          name:"LLM Security",              importance:"medium",  category:"cybersecurity", aliases:["prompt injection","llm security","ai red teaming","jailbreak","retrieval poisoning"] },
  // ─── Cloud / DevOps ──────────────────────────────────────────────────────
  aws:                    { id:"aws",                   name:"AWS",                       importance:"high",    category:"cloud_devops",  aliases:["amazon web services","ec2","s3","lambda","rds","iam","vpc","aws cloud","boto3"] },
  gcp:                    { id:"gcp",                   name:"GCP",                       importance:"medium",  category:"cloud_devops",  aliases:["google cloud platform","google cloud","gce","gke","bigquery"] },
  azure:                  { id:"azure",                 name:"Azure",                     importance:"medium",  category:"cloud_devops",  aliases:["microsoft azure","azure devops","azure cloud"] },
  docker:                 { id:"docker",                name:"Docker",                    importance:"high",    category:"cloud_devops",  aliases:["containers","dockerfile","containerization","docker compose"] },
  kubernetes:             { id:"kubernetes",            name:"Kubernetes",                importance:"high",    category:"cloud_devops",  aliases:["k8s","helm","helm charts","container orchestration"] },
  terraform:              { id:"terraform",             name:"Terraform",                 importance:"medium",  category:"cloud_devops",  aliases:["infrastructure as code","iac","terraform modules"] },
  linux:                  { id:"linux",                 name:"Linux",                     importance:"high",    category:"cloud_devops",  aliases:["ubuntu","debian","centos","alpine","unix","bash","shell scripting","linux administration"] },
  ci_cd:                  { id:"ci_cd",                 name:"CI/CD",                     importance:"medium",  category:"cloud_devops",  aliases:["github actions","jenkins","gitlab ci","continuous integration","continuous deployment","pipeline"] },
  observability:          { id:"observability",         name:"Observability & Monitoring",importance:"medium",  category:"cloud_devops",  aliases:["monitoring","logging","tracing","prometheus","grafana","opentelemetry","datadog","sentry"] },
  // ─── Backend / Systems ───────────────────────────────────────────────────
  python:                 { id:"python",                name:"Python",                    importance:"high",    category:"backend",       aliases:["py","python3","python programming","python scripting"] },
  golang:                 { id:"golang",                name:"Go (Golang)",               importance:"medium",  category:"backend",       aliases:["go","golang","go lang"] },
  java:                   { id:"java",                  name:"Java",                      importance:"medium",  category:"backend",       aliases:["java programming","spring","spring boot"] },
  cpp:                    { id:"cpp",                   name:"C++",                       importance:"medium",  category:"backend",       aliases:["c++","cpp","c plus plus"] },
  rust:                   { id:"rust",                  name:"Rust",                      importance:"low",     category:"backend",       aliases:["rust lang","rust programming"] },
  nodejs:                 { id:"nodejs",                name:"Node.js",                   importance:"medium",  category:"backend",       aliases:["node","node.js","nodejs","expressjs","express"] },
  fastapi:                { id:"fastapi",               name:"FastAPI",                   importance:"medium",  category:"backend",       aliases:["fast api","fastapi framework"] },
  postgresql:             { id:"postgresql",            name:"PostgreSQL",                importance:"medium",  category:"backend",       aliases:["postgres","postgresql","psql","sql database"] },
  mongodb:                { id:"mongodb",               name:"MongoDB",                   importance:"medium",  category:"backend",       aliases:["mongo","mongodb","nosql","document database"] },
  redis:                  { id:"redis",                 name:"Redis",                     importance:"medium",  category:"backend",       aliases:["redis cache","in-memory cache","redis database"] },
  concurrency:            { id:"concurrency",           name:"Concurrency & Async",       importance:"medium",  category:"backend",       aliases:["multithreading","async","asyncio","parallelism","goroutines","threading","concurrent"] },
  microservices:          { id:"microservices",         name:"Microservices",             importance:"medium",  category:"backend",       aliases:["distributed systems","service-oriented","soa","microservice architecture"] },
  websockets:             { id:"websockets",            name:"WebSockets",                importance:"medium",  category:"backend",       aliases:["websocket","real-time communication","socket.io","ws"] },
  networking_fundamentals:{ id:"networking_fundamentals",name:"Networking Fundamentals", importance:"medium",  category:"backend",       aliases:["tcp/ip","dns","http","https","sockets","networking","osi model","packet","protocol"] },
  // ─── Frontend ────────────────────────────────────────────────────────────
  react:                  { id:"react",                 name:"React",                     importance:"medium",  category:"frontend",      aliases:["react.js","reactjs","react hooks"] },
  nextjs:                 { id:"nextjs",                name:"Next.js",                   importance:"medium",  category:"frontend",      aliases:["nextjs","next.js","next js"] },
  typescript:             { id:"typescript",            name:"TypeScript",                importance:"medium",  category:"frontend",      aliases:["ts","typescript"] },
  javascript:             { id:"javascript",            name:"JavaScript",                importance:"medium",  category:"frontend",      aliases:["js","es6","javascript","ecmascript"] },
  // ─── ML / AI ─────────────────────────────────────────────────────────────
  machine_learning:       { id:"machine_learning",      name:"Machine Learning",          importance:"medium",  category:"ml_ai",         aliases:["ml","machine learning","ml engineering","sklearn","scikit-learn"] },
  deep_learning:          { id:"deep_learning",         name:"Deep Learning",             importance:"medium",  category:"ml_ai",         aliases:["neural networks","deep learning","pytorch","tensorflow","keras"] },
  llm:                    { id:"llm",                   name:"LLMs / Generative AI",      importance:"medium",  category:"ml_ai",         aliases:["llm","large language model","gpt","generative ai","rag","langchain","transformers"] },
};

// Build fast lookup: alias → canonical id (sorted by length DESC to prevent partial matches)
const ONTOLOGY_ALIAS_MAP: Array<{ pattern: string; id: string }> = [];
(function buildAliasMap() {
  Object.values(CAPABILITY_ONTOLOGY).forEach(cap => {
    ONTOLOGY_ALIAS_MAP.push({ pattern: cap.name.toLowerCase(), id: cap.id });
    cap.aliases.forEach(alias => ONTOLOGY_ALIAS_MAP.push({ pattern: alias.toLowerCase(), id: cap.id }));
  });
  ONTOLOGY_ALIAS_MAP.sort((a, b) => b.pattern.length - a.pattern.length);
})();

// ─── HEURISTICS: which capabilities are plausibly "Unknown" for CS students ────
// Based on: degree in CS/IT/ECE, web project present, cloud project present.
const HEURISTIC_RULES: Array<{
  capabilityId: string;
  trigger: (ctx: { isCSBranch: boolean; hasWebProject: boolean; hasCloudProject: boolean; skillTexts: string[] }) => boolean;
}> = [
  { capabilityId: "linux",                  trigger: ctx => ctx.isCSBranch },
  { capabilityId: "networking_fundamentals",trigger: ctx => ctx.isCSBranch },
  { capabilityId: "python",                 trigger: ctx => ctx.isCSBranch },
  { capabilityId: "xss",                    trigger: ctx => ctx.hasWebProject },
  { capabilityId: "api_security",           trigger: ctx => ctx.hasWebProject },
  { capabilityId: "owasp_top_10",           trigger: ctx => ctx.hasWebProject },
  { capabilityId: "cloud_security",         trigger: ctx => ctx.hasCloudProject },
  { capabilityId: "ci_cd",                  trigger: ctx => ctx.hasCloudProject || ctx.hasWebProject },
  { capabilityId: "observability",          trigger: ctx => ctx.hasCloudProject },
];

// ═══════════════════════════════════════════════════════════════════════════
// STAGE 1: Capability Extractor — Browser LLM → Ontology Normalization
// ═══════════════════════════════════════════════════════════════════════════

function normalizeToCapabilityIds(rawConcepts: string[]): WorkspaceCapability[] {
  const found = new Map<string, WorkspaceCapability>();
  rawConcepts.forEach(concept => {
    const lower = concept.toLowerCase().trim();
    if (lower.length < 2) return;
    for (const entry of ONTOLOGY_ALIAS_MAP) {
      if (lower.includes(entry.pattern) || entry.pattern.includes(lower)) {
        if (!found.has(entry.id)) {
          const cap = CAPABILITY_ONTOLOGY[entry.id];
          found.set(entry.id, { id: cap.id, name: cap.name, importance: cap.importance, category: cap.category });
        }
        return;
      }
    }
  });
  return Array.from(found.values());
}

function deterministicExtractCapabilities(jdText: string): WorkspaceCapability[] {
  // Pure regex scan of JD text against ontology — deterministic fallback
  const lower = jdText.toLowerCase();
  const found = new Map<string, WorkspaceCapability>();
  ONTOLOGY_ALIAS_MAP.forEach(entry => {
    const escaped = entry.pattern.replace(/[-\/\\^$*+?.()|[\]{}]/g, "\\$&");
    if (new RegExp(`\\b${escaped}\\b`).test(lower)) {
      if (!found.has(entry.id)) {
        const cap = CAPABILITY_ONTOLOGY[entry.id];
        found.set(entry.id, { id: cap.id, name: cap.name, importance: cap.importance, category: cap.category });
      }
    }
  });
  return Array.from(found.values());
}

async function extractCapabilities(jdText: string, companyName: string, modelType: string): Promise<WorkspaceCapability[]> {
  // Try browser LLM first
  try {
    const prompt = `Extract the technical skills, tools, and domain capabilities required by this job description.
Return ONLY a JSON array of strings, each being one specific technical capability. Do not include soft skills.
Company: ${companyName}
Job Description: ${jdText.substring(0, 900)}
Return ONLY the JSON array like: ["OWASP Top 10","Burp Suite","Python","Linux","Docker"]`;
    const raw = await generateInBrowser({ modelType, prompt, maxTokens: 256 });
    const parsed: string[] = JSON.parse(parseRobustLLMJSON(raw));
    if (Array.isArray(parsed) && parsed.length > 0) {
      const normalized = normalizeToCapabilityIds(parsed);
      if (normalized.length > 0) return normalized;
    }
  } catch (e) {
    console.warn("[Stage 1] Browser LLM failed, using deterministic fallback:", e);
  }
  // Deterministic fallback
  return deterministicExtractCapabilities(jdText);
}

// ═══════════════════════════════════════════════════════════════════════════
// STAGE 2: Evidence Extractor — deterministic, no LLM
// ═══════════════════════════════════════════════════════════════════════════

function extractResumeEvidence(resumeData: any): UserEvidence[] {
  const evidence: UserEvidence[] = [];

  // Skills section — direct match
  const skills: string[] = resumeData.skills || [];
  skills.forEach(skill => {
    const lower = skill.toLowerCase().trim();
    for (const entry of ONTOLOGY_ALIAS_MAP) {
      if (lower.includes(entry.pattern) || entry.pattern.includes(lower)) {
        evidence.push({ capabilityId: entry.id, text: skill, source: "resume", verified: true });
        return;
      }
    }
  });

  // Projects — scan tech + description
  const projects: any[] = resumeData.projects || [];
  projects.forEach((p, idx) => {
    const combined = `${p.title || ""} ${p.tech || ""} ${p.description || ""}`.toLowerCase();
    ONTOLOGY_ALIAS_MAP.forEach(entry => {
      if (new RegExp(`\\b${entry.pattern.replace(/[-\/\\^$*+?.()|[\]{}]/g, "\\$&")}\\b`).test(combined)) {
        evidence.push({ capabilityId: entry.id, text: `Project "${p.title}": ${entry.pattern}`, source: "resume", verified: true });
      }
    });
  });

  // Experience — scan description
  const experiences: any[] = resumeData.experience || [];
  experiences.forEach(exp => {
    const combined = `${exp.company || ""} ${exp.role || ""} ${exp.description || ""}`.toLowerCase();
    ONTOLOGY_ALIAS_MAP.forEach(entry => {
      if (new RegExp(`\\b${entry.pattern.replace(/[-\/\\^$*+?.()|[\]{}]/g, "\\$&")}\\b`).test(combined)) {
        evidence.push({ capabilityId: entry.id, text: `Experience at "${exp.company}": ${entry.pattern}`, source: "resume", verified: true });
      }
    });
  });

  return evidence;
}

// ═══════════════════════════════════════════════════════════════════════════
// STAGE 3: Capability Mapper — heuristic 4-state classifier
// ═══════════════════════════════════════════════════════════════════════════

function buildHeuristicContext(resumeData: any): { isCSBranch: boolean; hasWebProject: boolean; hasCloudProject: boolean; skillTexts: string[] } {
  const branch = (resumeData.education?.[0]?.branch || resumeData.personal?.branch || "").toLowerCase();
  const isCSBranch = /computer|software|information|cse|it\b|ece|electronics/.test(branch);
  const projects: any[] = resumeData.projects || [];
  const hasWebProject = projects.some(p => /react|flask|django|node|express|html|css|javascript|frontend|backend|api|web/.test(`${p.tech || ""} ${p.description || ""}`.toLowerCase()));
  const hasCloudProject = projects.some(p => /aws|gcp|azure|docker|kubernetes|cloud|deploy|heroku|vercel|netlify/.test(`${p.tech || ""} ${p.description || ""}`.toLowerCase()));
  const skillTexts = (resumeData.skills || []).map((s: string) => s.toLowerCase());
  return { isCSBranch, hasWebProject, hasCloudProject, skillTexts };
}

function mapCapabilityStates(capabilities: WorkspaceCapability[], evidence: UserEvidence[], resumeData: any): CapabilityCoverage[] {
  const ctx = buildHeuristicContext(resumeData);
  return capabilities.map(cap => {
    const matching = evidence.filter(e => e.capabilityId === cap.id);

    if (matching.length >= 2 || (matching.length === 1 && matching[0].source === "resume" && matching[0].text.toLowerCase().includes(cap.name.toLowerCase().split(" ")[0]))) {
      return { capability: cap, state: "strong" as EvidenceState, matchedEvidence: matching, reasoning: `Found ${matching.length} evidence item(s) directly referencing this capability.` };
    }

    if (matching.length === 1) {
      return { capability: cap, state: "weak" as EvidenceState, matchedEvidence: matching, reasoning: `Found indirect evidence: "${matching[0].text.substring(0, 60)}..."` };
    }

    // No direct evidence — check heuristics for Unknown
    const heuristic = HEURISTIC_RULES.find(r => r.capabilityId === cap.id && r.trigger(ctx));
    if (heuristic) {
      return { capability: cap, state: "unknown" as EvidenceState, matchedEvidence: [], reasoning: `No direct evidence found, but statistically likely given your background (CS branch: ${ctx.isCSBranch}, web project: ${ctx.hasWebProject}, cloud project: ${ctx.hasCloudProject}).` };
    }

    return { capability: cap, state: "missing" as EvidenceState, matchedEvidence: [], reasoning: "No evidence found and no heuristic path available. This is a specialized capability not commonly implied by your profile." };
  });
}

// ═══════════════════════════════════════════════════════════════════════════
// SCORE: Resume Readiness Score (deterministic)
// ═══════════════════════════════════════════════════════════════════════════

const IMPORTANCE_WEIGHT: Record<WorkspaceCapability["importance"], number> = { critical: 4, high: 3, medium: 2, low: 1 };
const STATE_SCORE: Record<EvidenceState, number> = { strong: 100, weak: 50, unknown: 25, missing: 0 };

function calculateReadinessScore(coverages: CapabilityCoverage[]): number {
  if (coverages.length === 0) return 0;
  const totalWeight = coverages.reduce((s, c) => s + IMPORTANCE_WEIGHT[c.capability.importance], 0);
  const weightedScore = coverages.reduce((s, c) => s + IMPORTANCE_WEIGHT[c.capability.importance] * STATE_SCORE[c.state], 0);
  return Math.round(weightedScore / totalWeight);
}

// ═══════════════════════════════════════════════════════════════════════════
// STAGE 4: Question Generator — browser LLM per capability
// ═══════════════════════════════════════════════════════════════════════════

async function generateEvidenceQuestion(coverage: CapabilityCoverage, modelType: string): Promise<EvidenceQuestion> {
  const cap = coverage.capability;
  const fallbackQuestion = `Have you worked with ${cap.name} in any projects, labs, coursework, or competitions? If yes, describe what you did and the tools you used.`;
  try {
    const prompt = `You are an expert technical recruiter conducting a resume enrichment interview.
Generate ONE targeted question to determine whether the candidate has real experience with "${cap.name}" that is not documented in their resume.
Do NOT ask generic questions. Ask for concrete evidence: projects, labs, CTFs, coursework, competitions, bug bounties, or research.
Return ONLY a JSON object: {"question": "..."}
Capability: ${cap.name} (Category: ${cap.category})
Current Evidence Status: ${coverage.state} — ${coverage.reasoning}`;
    const raw = await generateInBrowser({ modelType, prompt, maxTokens: 128 });
    const parsed = JSON.parse(parseRobustLLMJSON(raw));
    const q = typeof parsed === "object" && parsed.question ? String(parsed.question) : fallbackQuestion;
    return { id: `q_${cap.id}_${Date.now()}`, capabilityId: cap.id, capabilityName: cap.name, text: q, answer: "", stableKey: normalizeStableKey(`capability:${cap.id}`) };
  } catch (e) {
    console.warn(`[Stage 4] LLM question generation failed for ${cap.name}:`, e);
    return { id: `q_${cap.id}_${Date.now()}`, capabilityId: cap.id, capabilityName: cap.name, text: fallbackQuestion, answer: "", stableKey: normalizeStableKey(`capability:${cap.id}`) };
  }
}

// ═══════════════════════════════════════════════════════════════════════════
// STAGE 5: Evidence Structurer — browser LLM converts answer → vault entry
// ═══════════════════════════════════════════════════════════════════════════

async function structureAnswer(question: EvidenceQuestion, rawAnswer: string, modelType: string): Promise<{ evidence: UserEvidence; verification: CapabilityVerification }> {
  const verification: CapabilityVerification = {
    capabilityId: question.capabilityId,
    verified: rawAnswer.trim().length > 20,
    source: "user_answer",
    lastVerifiedAt: new Date().toISOString().split("T")[0],
    evidenceSummary: rawAnswer.trim().substring(0, 120),
  };
  const evidence: UserEvidence = {
    capabilityId: question.capabilityId,
    text: rawAnswer.trim(),
    source: "vault",
    verified: true,
  };
  return { evidence, verification };
}

// ═══════════════════════════════════════════════════════════════════════════
// STAGE 6: Patch Generator — browser LLM, strict grounding
// ═══════════════════════════════════════════════════════════════════════════

async function generateResumePatches(
  masterResume: any,
  vaultEvidence: UserEvidence[],
  capabilities: WorkspaceCapability[],
  modelType: string
): Promise<ResumePatch[]> {
  const patches: ResumePatch[] = [];

  // Skills patches — deterministic: add confirmed vault skills to skills list
  const existingSkills = new Set((masterResume.skills || []).map((s: string) => s.toLowerCase().trim()));
  vaultEvidence.forEach(e => {
    const cap = capabilities.find(c => c.id === e.capabilityId);
    if (cap && !existingSkills.has(cap.name.toLowerCase())) {
      patches.push({ section: "skills", action: "add", content: cap.name, reasoning: `Vault evidence confirms: "${e.text.substring(0, 60)}"` });
    }
  });

  // Project enhancement patches — LLM with strict prompt
  const projects: any[] = masterResume.projects || [];
  for (let i = 0; i < Math.min(projects.length, 3); i++) {
    const p = projects[i];
    const relevantEvidence = vaultEvidence.filter(e => e.text.toLowerCase().includes(p.title?.toLowerCase() || "---") || p.description?.toLowerCase().includes(CAPABILITY_ONTOLOGY[e.capabilityId]?.name.toLowerCase() || ""));
    if (relevantEvidence.length === 0) continue;
    try {
      const prompt = `You are a resume editor. Suggest ONE enhancement to this project description using ONLY the evidence provided.
STRICT RULES: Do NOT invent tools, metrics, or projects. Only use the provided evidence. If evidence is insufficient, return null.
Project: ${p.title}
Current description: ${p.description || "(empty)"}
Evidence from vault: ${relevantEvidence.map(e => e.text).join("; ")}
Return ONLY JSON: {"enhancement": "..."} or {"enhancement": null}`;
      const raw = await generateInBrowser({ modelType, prompt, maxTokens: 128 });
      const parsed = JSON.parse(parseRobustLLMJSON(raw));
      if (parsed?.enhancement && typeof parsed.enhancement === "string") {
        patches.push({ section: `project_${i}`, action: "enhance", content: parsed.enhancement, reasoning: `Grounded in vault evidence for project "${p.title}"` });
      }
    } catch (e) { /* skip this project */ }
  }

  return patches;
}

function applyPatches(masterResume: any, patches: ResumePatch[]): any {
  const tailored = JSON.parse(JSON.stringify(masterResume));
  if (!tailored.skills) tailored.skills = [];
  if (!tailored.projects) tailored.projects = [];

  patches.forEach(patch => {
    if (patch.section === "skills" && patch.action === "add") {
      const existing = tailored.skills.map((s: string) => s.toLowerCase().trim());
      if (!existing.includes(patch.content.toLowerCase().trim())) {
        tailored.skills.push(patch.content);
      }
    } else if (patch.section.startsWith("project_") && patch.action === "enhance") {
      const idx = parseInt(patch.section.split("_")[1]);
      if (tailored.projects[idx]) {
        const existing = tailored.projects[idx].description || "";
        tailored.projects[idx].description = existing ? `${existing} ${patch.content}` : patch.content;
      }
    } else if (patch.section === "summary" && (patch.action === "add" || patch.action === "rephrase")) {
      tailored.summary = patch.content;
    }
  });

  return tailored;
pat7 = re.compile(
    r"  const handleSaveToVault = async \(\) => \{.+?\r\n  \};",
    re.DOTALL
)
m7 = pat7.search(src)
if not m7:
    print("FAIL [7:handleSaveToVault] — not found")
    sys.exit(1)

NEW7 = crlf("""  const handleSaveToVault = async () => {
    if (!masterResume || !encryptionKey) {
      setErrorMsg("Vault session key missing. Please ensure your Vault is unlocked.");
      return;
    }
    setSavingVault(true);
    try {
      // Stage 5: Structure answers and update vault
      const structuredResults = await Promise.all(
        evidenceQuestions
          .filter(q => (answers[q.id] || "").trim().length > 0)
          .map(q => structureAnswer(q, answers[q.id] || "", atsModel))
      );

      const newVerifications = structuredResults.map(r => r.verification);
      const updatedCacheMap = { ...verificationCache };
      newVerifications.forEach(v => { updatedCacheMap[v.capabilityId] = v; });

      // Save as VaultQA entries (stableKey = capability:<id>)
      const existingVault: VaultQA[] = masterResume.context_vault || [];
      const updatedVault = [...existingVault];

      evidenceQuestions.filter(q => (answers[q.id] || "").trim().length > 0).forEach(q => {
        const newEntry: VaultQA = { stableKey: q.stableKey, question: q.text, answer: answers[q.id].trim(), timestamp: new Date().toISOString() };
        const idx = updatedVault.findIndex(v => v.stableKey === q.stableKey);
        if (idx !== -1) updatedVault[idx] = newEntry; else updatedVault.push(newEntry);
      });

      const updatedMaster = {
        ...masterResume,
        context_vault: updatedVault,
        capability_verifications: Object.values(updatedCacheMap),
      };
      await api.put("/resumes/me", { template: selectedTemplate, resume_data: updatedMaster });
      setMasterResume(updatedMaster);
      setVerificationCache(updatedCacheMap);

      // Refresh score
      const vaultEvidence: UserEvidence[] = updatedVault.filter(v => v.stableKey && v.answer.trim().length > 20).map(v => ({ capabilityId: v.stableKey!.replace("capability:", ""), text: v.answer.trim(), source: "vault" as const, verified: true }));
      const allEvidence = [...extractResumeEvidence(updatedMaster), ...vaultEvidence];
      const newCoverages = mapCapabilityStates(workspaceCapabilities, allEvidence, updatedMaster);
      setCoverages(newCoverages);
      setReadinessScore(calculateReadinessScore(newCoverages));

      showSuccess("Answers saved to vault! Your Resume Readiness Score has been updated.");
      setCopilotTab("readiness");
    } catch (err: any) {
      console.error("Failed to save to vault", err);
      setErrorMsg(err.response?.data?.detail || "Failed to save answers to secure vault.");
    } finally {
      setSavingVault(false);
    }
  };""")

src = src[:m7.start()] + NEW7 + src[m7.end():]
print("OK   [7:handleSaveToVault]")

# ═══════════════════════════════════════════════════════════════════════════════
# PATCH 8: Replace handleGenerateTailoredResume to use patch-based tailoring
# ═══════════════════════════════════════════════════════════════════════════════
pat8 = re.compile(
    r"  const handleGenerateTailoredResume = async \(\) => \{.+?\r\n  \};",
    re.DOTALL
)
m8 = pat8.search(src)
if not m8:
    print("FAIL [8:handleGenerateTailoredResume] — not found")
    sys.exit(1)

NEW8 = crlf("""  const handleGenerateTailoredResume = async () => {
    if (!masterResume) {
      setErrorMsg("No master resume found. Cannot generate tailored resume.");
      return;
    }
    setCalculatingATS(true);
    setErrorMsg("");
    setSuccessMsg("");
    try {
      // Load all vault evidence
      const vaultEntries: VaultQA[] = masterResume.context_vault || [];
      const vaultEvidence: UserEvidence[] = vaultEntries
        .filter(v => v.stableKey && v.answer.trim().length > 20)
        .map(v => ({ capabilityId: v.stableKey!.replace("capability:", ""), text: v.answer.trim(), source: "vault" as const, verified: true }));

      // Stage 6: Generate patch operations (not full rewrite)
      setLocalStatusMessage("Generating resume patches from evidence vault...");
      const patches = await generateResumePatches(masterResume, vaultEvidence, workspaceCapabilities, atsModel);
      setPendingPatches(patches);

      // Apply patches deterministically
      const tailored = applyPatches(masterResume, patches);
      setTailoredResumeData(tailored);

      showSuccess(`Generated ${patches.length} targeted patch(es). Tailored resume is ready.`);
      setCopilotTab("patches");
    } catch (err: any) {
      setErrorMsg(err.message || "Failed to generate tailored resume.");
    } finally {
      setCalculatingATS(false);
      setLocalStatusMessage("");
    }
  };""")

src = src[:m8.start()] + NEW8 + src[m8.end():]
print("OK   [8:handleGenerateTailoredResume]")

# ═══════════════════════════════════════════════════════════════════════════════
# PATCH 9: Update updateCopilotAnswer references
# ═══════════════════════════════════════════════════════════════════════════════
OLD9 = crlf("  const updateCopilotAnswer = (id: string, val: string) => {\n    setAnswers(prev => ({ ...prev, [id]: val }));\n    setCopilotQuestions(prev => prev.map(q => q.id === id ? { ...q, answer: val } : q));\n  };")
NEW9 = crlf("  const updateCopilotAnswer = (id: string, val: string) => {\n    setAnswers(prev => ({ ...prev, [id]: val }));\n    setEvidenceQuestions(prev => prev.map(q => q.id === id ? { ...q, answer: val } : q));\n  };")
exact_replace("9:updateCopilotAnswer", OLD9, NEW9)

# ═══════════════════════════════════════════════════════════════════════════════
# PATCH 10: Replace JSX gaps render block with new Readiness Panel
# ═══════════════════════════════════════════════════════════════════════════════
# Find the gap render section (evidenceGaps.map block)
pat10 = re.compile(
    r"                              <div className=\"grid grid-cols-1 md:grid-cols-2 gap-4\">\r\n"
    r"                                \{evidenceGaps\.map\(\(gap, idx\) => \{.+?\}\)}\r\n"
    r"                              </div>",
    re.DOTALL
)
m10 = pat10.search(src)
if not m10:
    print("FAIL [10:gaps-render] — evidenceGaps.map block not found")
    sys.exit(1)

BADGE_COLORS: dict = {}  # just for reference
NEW10 = crlf("""                              {/* ── Resume Readiness Score ──────────────────── */}
                              {readinessScore !== null && (
                                <div className="mb-4 p-4 border border-border bg-background/50 rounded-sm">
                                  <div className="flex justify-between items-center mb-2">
                                    <span className="text-[10px] font-black uppercase tracking-widest text-muted-foreground">Resume Readiness Score</span>
                                    <span className={`text-lg font-black ${readinessScore >= 70 ? "text-emerald-400" : readinessScore >= 40 ? "text-amber-400" : "text-red-400"}`}>
                                      {readinessScore}%
                                    </span>
                                  </div>
                                  <div className="w-full h-1.5 bg-border rounded-full overflow-hidden">
                                    <div className={`h-full rounded-full transition-all duration-700 ${readinessScore >= 70 ? "bg-emerald-500" : readinessScore >= 40 ? "bg-amber-500" : "bg-red-500"}`} style={{ width: `${readinessScore}%` }} />
                                  </div>
                                </div>
                              )}

                              {/* ── 4-State Coverage Grid ─────────────────────── */}
                              {(["strong","weak","unknown","missing"] as EvidenceState[]).map(state => {
                                const items = coverages.filter(c => c.state === state);
                                if (items.length === 0) return null;
                                const config = {
                                  strong:  { label:"✓ Strong Evidence",          color:"text-emerald-400", border:"border-emerald-500/25 bg-emerald-500/5" },
                                  weak:    { label:"⚠ Needs Better Evidence",    color:"text-amber-400",   border:"border-amber-500/25 bg-amber-500/5" },
                                  unknown: { label:"? Need Verification",         color:"text-blue-400",    border:"border-blue-500/25 bg-blue-500/5" },
                                  missing: { label:"✗ No Evidence Found",         color:"text-red-400",     border:"border-red-500/25 bg-red-500/5" },
                                }[state];
                                return (
                                  <div key={state} className={`border ${config.border} rounded-sm p-3 mb-3`}>
                                    <div className={`text-[9px] font-black uppercase tracking-widest mb-2 ${config.color}`}>{config.label} ({items.length})</div>
                                    <div className="flex flex-wrap gap-1.5">
                                      {items.map(c => (
                                        <span key={c.capability.id} className="text-[10px] font-bold text-foreground bg-muted/40 px-2 py-0.5 rounded-sm border border-border">
                                          {c.capability.name}
                                        </span>
                                      ))}
                                    </div>
                                  </div>
                                );
                              })}""")

src = src[:m10.start()] + NEW10 + src[m10.end():]
print("OK   [10:readiness-panel-jsx]")

# ═══════════════════════════════════════════════════════════════════════════════
# PATCH 11: Replace questions render block (copilotQuestions.map)
# ═══════════════════════════════════════════════════════════════════════════════
pat11 = re.compile(
    r"                              <div className=\"grid grid-cols-1 md:grid-cols-2 gap-4\">\r\n"
    r"                                \{copilotQuestions\.map\(\(q\) => \{.+?\}\)}\r\n"
    r"                              </div>",
    re.DOTALL
)
m11 = pat11.search(src)
if not m11:
    print("FAIL [11:questions-render] — copilotQuestions.map block not found")
    sys.exit(1)

NEW11 = crlf("""                              <div className="space-y-4">
                                {evidenceQuestions.map((q) => {
                                  const feedback = getAnswerFeedback(answers[q.id] || "");
                                  return (
                                    <div key={q.id} className="border border-border bg-background p-4 space-y-3">
                                      <div className="space-y-1">
                                        <div className="flex items-center gap-2">
                                          <span className="px-2 py-0.5 text-[8px] font-black border border-blue-500/35 text-blue-400 bg-blue-500/5 uppercase tracking-wider">
                                            ? {q.capabilityName}
                                          </span>
                                        </div>
                                        <p className="text-xs font-bold text-foreground leading-normal">{q.text}</p>
                                      </div>
                                      <div className="space-y-2">
                                        <textarea
                                          id={`copilot-answer-${q.id}`}
                                          value={answers[q.id] || ""}
                                          onChange={e => updateCopilotAnswer(q.id, e.target.value)}
                                          placeholder="Describe your experience — include specific tools, projects, or metrics..."
                                          rows={3}
                                          className="w-full text-xs bg-muted/20 border border-border rounded-sm p-2.5 text-foreground placeholder:text-muted-foreground/60 resize-none focus:outline-none focus:border-accent/60 font-medium"
                                        />
                                        {(answers[q.id] || "").trim().length > 0 && (
                                          <p className={`text-[10px] font-bold ${feedback.status === "strong" ? "text-emerald-400" : "text-amber-400"}`}>
                                            {feedback.feedback}
                                          </p>
                                        )}
                                      </div>
                                    </div>
                                  );
                                })}
                              </div>""")

src = src[:m11.start()] + NEW11 + src[m11.end():]
print("OK   [11:questions-render-jsx]")

# ═══════════════════════════════════════════════════════════════════════════════
# PATCH 12: Fix button references (generateCopilotQuestions → runAnalysis)
# ═══════════════════════════════════════════════════════════════════════════════
old12 = "onClick={generateCopilotQuestions}"
new12 = "onClick={runAnalysis}"
count12 = src.count(old12)
if count12 == 0:
    print("WARN [12:button-ref] — generateCopilotQuestions onClick not found, skipping")
else:
    src = src.replace(old12, new12)
    print(f"OK   [12:button-ref] ({count12} occurrence(s))")

# Fix tab references
src = src.replace('"gaps"', '"readiness"', 1) if '"gaps"' in src else src
print("OK   [12b:tab-ref-fixup]")

# ═══════════════════════════════════════════════════════════════════════════════
# WRITE BACK
# ═══════════════════════════════════════════════════════════════════════════════
new_len = len(src)
if new_len < orig_len * 0.7:
    print(f"SAFETY ABORT: file shrank too much ({orig_len} -> {new_len})")
    sys.exit(1)

with open(FILE, "w", encoding="utf-8", newline="") as f:
    f.write(src)

print(f"\nAll patches applied. {orig_len} -> {new_len} chars (+{new_len-orig_len})")
