"use client";

import { ChangeEvent, FormEvent, useRef, useState } from "react";
import { Check, ImagePlus, Loader2, MessageSquareWarning, Send, X } from "lucide-react";
import { isAxiosError } from "axios";
import api from "@/lib/api";

const MAX_FILES = 3, MAX_FILE_SIZE = 5 * 1024 * 1024;
export default function FeedbackDialog({ className = "" }: { className?: string }) {
  const [open, setOpen] = useState(false), [message, setMessage] = useState(""), [files, setFiles] = useState<File[]>([]), [error, setError] = useState(""), [submitting, setSubmitting] = useState(false), [sent, setSent] = useState(false);
  const inputRef = useRef<HTMLInputElement>(null);
  const close = () => { if (!submitting) { setOpen(false); setError(""); setSent(false); } };
  const addFiles = (event: ChangeEvent<HTMLInputElement>) => { const chosen = Array.from(event.target.files || []); if (chosen.some(f => !f.type.startsWith("image/") || f.size > MAX_FILE_SIZE)) { setError("Attach images only, up to 5 MB each."); return; } setFiles(current => [...current, ...chosen].slice(0, MAX_FILES)); event.target.value = ""; };
  const submit = async (event: FormEvent) => { event.preventDefault(); if (message.trim().length < 8) { setError("Please describe the issue in a little more detail."); return; } setSubmitting(true); setError(""); try { const form = new FormData(); form.append("message", message.trim()); form.append("page_url", window.location.href); files.forEach(file => form.append("screenshots", file)); await api.post("/feedback", form, { headers: { "Content-Type": "multipart/form-data" } }); setSent(true); setMessage(""); setFiles([]); } catch (err: unknown) { const detail = isAxiosError<{ detail?: string }>(err) ? err.response?.data?.detail : undefined; setError(detail || "Could not send the report. Please try again."); } finally { setSubmitting(false); } };
  return <><button onClick={() => setOpen(true)} className={`flex w-full items-center justify-center gap-3 border-2 border-border bg-background px-4 py-2.5 text-xs font-bold tracking-wider uppercase text-muted-foreground shadow-[3px_3px_0_0_#DFE104] hover:border-accent hover:bg-accent hover:text-black transition-all ${className}`}><MessageSquareWarning size={14} /><span>Report an issue</span></button>{open && <div className="fixed inset-0 z-[100] flex items-center justify-center bg-black/70 p-4" role="dialog" aria-modal="true"><form onSubmit={submit} className="w-full max-w-lg border-2 border-border bg-background shadow-[8px_8px_0_0_#DFE104]"><div className="flex items-center justify-between border-b-2 border-border px-5 py-4"><div><h2 className="text-sm font-extrabold tracking-wider uppercase">Report an issue</h2><p className="mt-1 text-[10px] text-muted-foreground">This report goes directly to the NextUp team.</p></div><button type="button" onClick={close} className="border border-border p-2 hover:bg-muted" aria-label="Close"><X size={16} /></button></div>{sent ? <div className="p-8 text-center"><Check className="mx-auto mb-3 text-accent" size={28} /><p className="text-sm font-bold uppercase">Report sent</p><button type="button" onClick={close} className="mt-5 border-2 border-border px-5 py-2 text-xs font-bold uppercase hover:bg-accent hover:text-black">Close</button></div> : <div className="space-y-4 p-5"><textarea value={message} onChange={e => setMessage(e.target.value)} rows={6} maxLength={5000} placeholder="What happened? Include the company or page, what you expected, and what you saw." className="w-full resize-y border-2 border-border bg-card p-3 text-sm outline-none placeholder:text-muted-foreground focus:border-accent" /><input ref={inputRef} type="file" accept="image/*" multiple className="hidden" onChange={addFiles} /><div className="flex flex-wrap items-center gap-2"><button type="button" disabled={files.length >= MAX_FILES} onClick={() => inputRef.current?.click()} className="inline-flex items-center gap-2 border border-border px-3 py-2 text-[10px] font-bold uppercase hover:border-accent disabled:opacity-40"><ImagePlus size={14} /> Add screenshots</button>{files.map((file, i) => <span key={`${file.name}-${i}`} className="flex items-center gap-1 border border-border px-2 py-1 text-[10px] text-muted-foreground">{file.name}<button type="button" onClick={() => setFiles(current => current.filter((_, index) => index !== i))} aria-label={`Remove ${file.name}`}><X size={12} /></button></span>)}</div>{error && <p className="text-xs font-semibold text-red-500">{error}</p>}<button disabled={submitting} className="flex w-full items-center justify-center gap-2 bg-accent px-4 py-3 text-xs font-extrabold tracking-widest text-black uppercase disabled:opacity-60">{submitting ? <Loader2 className="animate-spin" size={15} /> : <Send size={15} />}{submitting ? "Sending" : "Send report"}</button></div>}</form></div>}</>;
}
