import os
import re
import sys
import jinja2
import logging
import subprocess
import tempfile
from typing import Dict, Any

logger = logging.getLogger("nextup.latex_renderer")

# Set up jinja2 environment with alternate delimiters to avoid conflict with LaTeX curly braces
latex_jinja_env = jinja2.Environment(
    block_start_string='\block{',
    block_end_string='}',
    variable_start_string='\var{',
    variable_end_string='}',
    comment_start_string='\comment{',
    comment_end_string='}',
    trim_blocks=True,
    autoescape=False,
    loader=jinja2.FileSystemLoader(os.path.join(os.path.dirname(os.path.dirname(os.path.dirname(__file__))), "storage", "latex_templates"))
)

def escape_latex(val: Any) -> str:
    """Escapes special LaTeX characters to avoid compilation failures."""
    if val is None:
        return ""
    if not isinstance(val, str):
        return str(val)
        
    # Map of special LaTeX characters to escaped strings
    conv = {
        '&': r'\&',
        '%': r'\%',
        '$': r'\$',
        '#': r'\#',
        '_': r'\_',
        '{': r'\{',
        '}': r'\}',
        '~': r'\textasciitilde{}',
        '^': r'\textasciicircum{}',
        '\\': r'\textbackslash{}',
    }
    
    regex = re.compile('|'.join(re.escape(str(key)) for key in sorted(conv.keys(), key=len, reverse=True)))
    return regex.sub(lambda match: conv[match.group()], val)

# Register filter
latex_jinja_env.filters['e_tex'] = escape_latex

def render_resume_to_pdf(template_name: str, content_json: dict) -> bytes:
    """
    Renders structured resume JSON into a LaTeX template and compiles to PDF.
    If pdflatex is not installed on the system, falls back to a clean PyMuPDF drawing.
    """
    template_file = f"{template_name.lower()}.tex.j2"
    
    # 1. Escape LaTeX characters recursively in content_json
    escaped_content = _escape_dict_recursive(content_json)
    
    try:
        template = latex_jinja_env.get_template(template_file)
        rendered_tex = template.render(**escaped_content)
    except Exception as e:
        logger.error(f"Failed to render LaTeX template {template_name}: {e}")
        # If template loading fails, fall back to PyMuPDF directly
        return _render_fallback_pdf(content_json)

    # 2. Check if pdflatex is available
    has_latex = False
    try:
        # Check pdflatex version
        result = subprocess.run(["pdflatex", "-version"], stdout=subprocess.PIPE, stderr=subprocess.PIPE, check=False)
        if result.returncode == 0:
            has_latex = True
    except Exception:
        pass

    if not has_latex:
        logger.warning("pdflatex compiler not found. Falling back to PyMuPDF rendering.")
        return _render_fallback_pdf(content_json)

    # 3. Compile LaTeX in a temp directory
    with tempfile.TemporaryDirectory() as temp_dir:
        tex_path = os.path.join(temp_dir, "resume.tex")
        with open(tex_path, "w", encoding="utf-8") as f:
            f.write(rendered_tex)

        try:
            # Run pdflatex twice for table alignments/page numbers
            for _ in range(2):
                result = subprocess.run(
                    ["pdflatex", "-interaction=nonstopmode", "-halt-on-error", "resume.tex"],
                    cwd=temp_dir,
                    stdout=subprocess.PIPE,
                    stderr=subprocess.PIPE,
                    timeout=15
                )
                if result.returncode != 0:
                    stderr_out = result.stderr.decode("utf-8", errors="ignore")
                    stdout_out = result.stdout.decode("utf-8", errors="ignore")
                    logger.error(f"LaTeX compile error output:\n{stdout_out}\n{stderr_out}")
                    raise RuntimeError("LaTeX compilation failed.")
            
            pdf_path = os.path.join(temp_dir, "resume.pdf")
            if os.path.exists(pdf_path):
                with open(pdf_path, "rb") as f:
                    return f.read()
            else:
                raise FileNotFoundError("resume.pdf was not generated by pdflatex.")
                
        except Exception as compile_err:
            logger.error(f"pdflatex compilation failed: {compile_err}. Falling back to PyMuPDF.")
            return _render_fallback_pdf(content_json)

def _escape_dict_recursive(data: Any) -> Any:
    if isinstance(data, dict):
        return {k: _escape_dict_recursive(v) for k, v in data.items()}
    elif isinstance(data, list):
        return [_escape_dict_recursive(v) for v in data]
    elif isinstance(data, str):
        return escape_latex(data)
    else:
        return data

def _render_fallback_pdf(content_json: dict) -> bytes:
    """Fallback compiler using PyMuPDF (fitz) to draw a clean resume preview."""
    import fitz
    logger.info("Generating beautifully styled fallback PDF using PyMuPDF.")
    
    doc = fitz.open()
    page = doc.new_page(width=595, height=842) # A4 dimensions
    
    # Define text colors and margins
    margin = 54
    y = 54
    width = 595 - (2 * margin)
    
    personal = content_json.get("personal", {})
    name = personal.get("name", "Student Resume").upper()
    email = personal.get("email", "")
    phone = personal.get("phone", "")
    linkedin = personal.get("linkedin", "")
    
    # 1. Header (Centered Name & Contact Info)
    page.insert_text((margin, y), name, fontsize=16, fontname="hebo", color=(0.1, 0.1, 0.1))
    y += 24
    
    contact_details = []
    if email: contact_details.append(email)
    if phone: contact_details.append(phone)
    if linkedin: contact_details.append(linkedin)
    contact_str = "  |  ".join(contact_details)
    page.insert_text((margin, y), contact_str, fontsize=9, fontname="helv", color=(0.4, 0.4, 0.4))
    y += 18
    
    # Draw horizontal divider
    shape = page.new_shape()
    shape.draw_line(fitz.Point(margin, y), fitz.Point(595 - margin, y))
    shape.finish(color=(0.8, 0.8, 0.8), width=1)
    shape.commit()
    y += 18
    
    # Helper to insert section title
    def add_section_header(title):
        nonlocal y
        y += 10
        page.insert_text((margin, y), title.upper(), fontsize=11, fontname="hebo", color=(0.2, 0.2, 0.5))
        y += 14
        shape = page.new_shape()
        shape.draw_line(fitz.Point(margin, y - 6), fitz.Point(180, y - 6))
        shape.finish(color=(0.2, 0.2, 0.5), width=1.5)
        shape.commit()
        
    # 2. Professional Summary
    summary = content_json.get("summary", "")
    if summary:
        add_section_header("Summary")
        rect = fitz.Rect(margin, y, 595 - margin, y + 45)
        page.insert_textbox(rect, summary, fontsize=9.5, fontname="helv", color=(0.2, 0.2, 0.2))
        y += 50
        
    # 3. Education
    education = content_json.get("education", [])
    if education:
        add_section_header("Education")
        for edu in education:
            if y > 750: break
            inst = edu.get("institution", "")
            deg = edu.get("degree", "")
            dates = edu.get("dates", "")
            gpa = edu.get("gpa", "")
            
            edu_str = f"{deg} - {inst} ({dates})"
            page.insert_text((margin, y), edu_str, fontsize=9.5, fontname="hebo", color=(0.1, 0.1, 0.1))
            if gpa:
                page.insert_text((595 - margin - 80, y), f"GPA: {gpa}", fontsize=9.5, fontname="hebo", color=(0.1, 0.1, 0.1))
            y += 16
            
    # 4. Skills
    skills = content_json.get("skills", [])
    if skills:
        add_section_header("Skills")
        if isinstance(skills, list):
            skills_str = ", ".join(skills)
        elif isinstance(skills, dict):
            skills_str = " | ".join(f"{k}: {', '.join(v)}" for k, v in skills.items())
        else:
            skills_str = str(skills)
            
        rect = fitz.Rect(margin, y, 595 - margin, y + 35)
        page.insert_textbox(rect, skills_str, fontsize=9.5, fontname="helv", color=(0.2, 0.2, 0.2))
        y += 40
        
    # 5. Experience
    experience = content_json.get("experience", [])
    if experience:
        add_section_header("Experience")
        for exp in experience:
            if y > 750: break
            comp = exp.get("company", "")
            role = exp.get("role", "")
            dates = exp.get("dates", "")
            desc = exp.get("description", "")
            
            exp_header = f"{role} at {comp} ({dates})"
            page.insert_text((margin, y), exp_header, fontsize=9.5, fontname="hebo", color=(0.1, 0.1, 0.1))
            y += 14
            
            if desc:
                # Split description bullet points
                bullets = desc.split("\n") if "\n" in desc else [desc]
                for b in bullets:
                    b_clean = b.strip().lstrip("-*•").strip()
                    if b_clean:
                        page.insert_text((margin + 12, y), f"•  {b_clean[:90]}", fontsize=9, fontname="helv", color=(0.2, 0.2, 0.2))
                        y += 12
            y += 6

    # 6. Projects
    projects = content_json.get("projects", [])
    if projects:
        add_section_header("Projects")
        for proj in projects:
            if y > 750: break
            title = proj.get("title", "")
            desc = proj.get("description", "")
            
            page.insert_text((margin, y), title, fontsize=9.5, fontname="hebo", color=(0.1, 0.1, 0.1))
            y += 14
            
            if desc:
                bullets = desc.split("\n") if "\n" in desc else [desc]
                for b in bullets:
                    b_clean = b.strip().lstrip("-*•").strip()
                    if b_clean:
                        page.insert_text((margin + 12, y), f"•  {b_clean[:90]}", fontsize=9, fontname="helv", color=(0.2, 0.2, 0.2))
                        y += 12
            y += 6

    return doc.write()
