import os
import re
import sys
import jinja2
import logging
import subprocess
import tempfile
from typing import Dict, Any

logger = logging.getLogger("nextup.latex_renderer")

# Set up jinja2 environment with alternate delimiters to avoid conflict with LaTeX curly braces
latex_jinja_env = jinja2.Environment(
    block_start_string=r'\block{',
    block_end_string='}',
    variable_start_string=r'\var{',
    variable_end_string='}',
    comment_start_string=r'\comment{',
    comment_end_string='}',
    trim_blocks=True,
    autoescape=False,
    loader=jinja2.FileSystemLoader(os.path.join(os.path.dirname(os.path.dirname(os.path.dirname(__file__))), "storage", "latex_templates"))
)

def escape_latex(val: Any) -> str:
    """Escapes special LaTeX characters to avoid compilation failures."""
    if val is None:
        return ""
    if not isinstance(val, str):
        return str(val)
        
    # Map of special LaTeX characters to escaped strings
    conv = {
        '&': r'\&',
        '%': r'\%',
        '$': r'\$',
        '#': r'\#',
        '_': r'\_',
        '{': r'\{',
        '}': r'\}',
        '~': r'\textasciitilde{}',
        '^': r'\textasciicircum{}',
        '\\': r'\textbackslash{}',
    }
    
    regex = re.compile('|'.join(re.escape(str(key)) for key in sorted(conv.keys(), key=len, reverse=True)))
    return regex.sub(lambda match: conv[match.group()], val)

# Register filter
latex_jinja_env.filters['e_tex'] = escape_latex

def render_resume_to_pdf(template_name: str, content_json: dict) -> bytes:
    """
    Renders structured resume JSON into a LaTeX template and compiles to PDF.
    If pdflatex is not installed on the system, falls back to a clean PyMuPDF drawing.
    """
    template_file = f"{template_name.lower()}.tex.j2"
    
    # 1. Escape LaTeX characters recursively in content_json
    escaped_content = _escape_dict_recursive(content_json)
    
    try:
        template = latex_jinja_env.get_template(template_file)
        rendered_tex = template.render(**escaped_content)
    except Exception as e:
        logger.error(f"Failed to render LaTeX template {template_name}: {e}")
        # If template loading fails, fall back to PyMuPDF directly
        return _render_fallback_pdf(content_json)

    # 2. Check if pdflatex is available
    has_latex = False
    try:
        # Check pdflatex version
        result = subprocess.run(["pdflatex", "-version"], stdout=subprocess.PIPE, stderr=subprocess.PIPE, check=False)
        if result.returncode == 0:
            has_latex = True
    except Exception:
        pass

    if not has_latex:
        logger.warning("pdflatex compiler not found. Falling back to PyMuPDF rendering.")
        return _render_fallback_pdf(content_json)

    # 3. Compile LaTeX in a temp directory
    with tempfile.TemporaryDirectory() as temp_dir:
        tex_path = os.path.join(temp_dir, "resume.tex")
        with open(tex_path, "w", encoding="utf-8") as f:
            f.write(rendered_tex)

        try:
            # Run pdflatex twice for table alignments/page numbers
            for _ in range(2):
                result = subprocess.run(
                    ["pdflatex", "-interaction=nonstopmode", "-halt-on-error", "resume.tex"],
                    cwd=temp_dir,
                    stdout=subprocess.PIPE,
                    stderr=subprocess.PIPE,
                    timeout=15
                )
                if result.returncode != 0:
                    stderr_out = result.stderr.decode("utf-8", errors="ignore")
                    stdout_out = result.stdout.decode("utf-8", errors="ignore")
                    logger.error(f"LaTeX compile error output:\n{stdout_out}\n{stderr_out}")
                    raise RuntimeError("LaTeX compilation failed.")
            
            pdf_path = os.path.join(temp_dir, "resume.pdf")
            if os.path.exists(pdf_path):
                with open(pdf_path, "rb") as f:
                    return f.read()
            else:
                raise FileNotFoundError("resume.pdf was not generated by pdflatex.")
                
        except Exception as compile_err:
            logger.error(f"pdflatex compilation failed: {compile_err}. Falling back to PyMuPDF.")
            return _render_fallback_pdf(content_json)

def _escape_dict_recursive(data: Any) -> Any:
    if isinstance(data, dict):
        return {k: _escape_dict_recursive(v) for k, v in data.items()}
    elif isinstance(data, list):
        return [_escape_dict_recursive(v) for v in data]
    elif isinstance(data, str):
        return escape_latex(data)
    else:
        return data

def _render_fallback_pdf(content_json: dict) -> bytes:
    """PDF renderer using PyMuPDF (the production path — no TeX on the Space).

    Renders EVERY section of the resume JSON with proper word-wrapping and
    automatic page breaks. The previous version drew single-line text capped
    at 90 chars on one page, which truncated every bullet and silently
    dropped links, patents, recognition and anything past ~750pt.
    """
    import fitz
    logger.info("Generating resume PDF using PyMuPDF renderer.")

    PAGE_W, PAGE_H = 595, 842  # A4
    MARGIN = 50
    BOTTOM = PAGE_H - 50

    INK = (0.1, 0.1, 0.1)
    BODY = (0.2, 0.2, 0.2)
    MUTED = (0.4, 0.4, 0.4)
    ACCENT = (0.2, 0.2, 0.5)

    doc = fitz.open()
    state = {"page": doc.new_page(width=PAGE_W, height=PAGE_H), "y": MARGIN}

    def ensure_space(needed: float):
        if state["y"] + needed > BOTTOM:
            state["page"] = doc.new_page(width=PAGE_W, height=PAGE_H)
            state["y"] = MARGIN

    def wrap(text_val: str, fontsize: float, fontname: str, width: float):
        """Greedy word-wrap using real glyph metrics."""
        words = str(text_val).split()
        lines, current = [], ""
        for word in words:
            candidate = f"{current} {word}".strip()
            if fitz.get_text_length(candidate, fontname=fontname, fontsize=fontsize) <= width:
                current = candidate
            else:
                if current:
                    lines.append(current)
                current = word
        if current:
            lines.append(current)
        return lines or [""]

    def draw_wrapped(text_val: str, *, x: float = MARGIN, fontsize: float = 9.5,
                     fontname: str = "helv", color=BODY, width: float = None,
                     line_height: float = None, link_uri: str = None):
        width = width or (PAGE_W - MARGIN - x)
        line_height = line_height or (fontsize + 3)
        for line in wrap(text_val, fontsize, fontname, width):
            ensure_space(line_height)
            state["page"].insert_text((x, state["y"]), line, fontsize=fontsize,
                                      fontname=fontname, color=color)
            if link_uri:
                text_w = fitz.get_text_length(line, fontname=fontname, fontsize=fontsize)
                state["page"].insert_link({
                    "kind": fitz.LINK_URI, "uri": link_uri,
                    "from": fitz.Rect(x, state["y"] - fontsize, x + text_w, state["y"] + 2),
                })
            state["y"] += line_height

    def split_bullets(desc):
        """Normalize a description into logical bullets.

        PDF-parsed resumes carry the ORIGINAL line wrapping: a newline is
        usually mid-sentence, not a new bullet. Splitting on raw newlines
        printed a stray '·' at the start of every wrapped line. A new bullet
        starts only at a bullet marker (•, -, *, ▪); marker-less lines are
        continuations of the previous bullet. Inline '•' separators (the AI
        emits single-line '• a • b' strings) also split.
        """
        if isinstance(desc, list):
            raw = [str(b) for b in desc]
        else:
            bullets = []
            for line in str(desc).split("\n"):
                stripped = line.strip()
                if not stripped:
                    continue
                if stripped[0] in "•-*▪·" or not bullets:
                    bullets.append(stripped.lstrip("•-*▪·").strip())
                else:
                    bullets[-1] += " " + stripped
            raw = bullets
        final = []
        for b in raw:
            parts = [p.strip() for p in re.split(r"\s*•\s*", b) if p.strip()]
            final.extend(parts if parts else [b.strip()])
        return [b for b in final if b]

    def draw_bullets(desc, indent: float = 12):
        """desc may be a newline-joined string or a list of bullet strings."""
        for b_clean in split_bullets(desc):
            draw_wrapped(f"•  {b_clean}", x=MARGIN + indent, fontsize=9,
                         line_height=12)

    def section_header(title: str):
        ensure_space(34)
        state["y"] += 10
        state["page"].insert_text((MARGIN, state["y"]), title.upper(), fontsize=11,
                                  fontname="hebo", color=ACCENT)
        state["y"] += 8
        shape = state["page"].new_shape()
        shape.draw_line(fitz.Point(MARGIN, state["y"]), fitz.Point(MARGIN + 130, state["y"]))
        shape.finish(color=ACCENT, width=1.5)
        shape.commit()
        state["y"] += 12

    def first_of(d: dict, *keys) -> str:
        for k in keys:
            v = d.get(k)
            if v:
                return str(v)
        return ""

    # ── 1. Header: name + contact + links ─────────────────────────────
    personal = content_json.get("personal", {}) or {}
    name = str(personal.get("name") or "Student Resume").upper()
    ensure_space(24)
    state["page"].insert_text((MARGIN, state["y"] + 12), name, fontsize=16,
                              fontname="hebo", color=INK)
    state["y"] += 30

    contact_parts = [p for p in (personal.get("email"), personal.get("phone"),
                                 personal.get("location")) if p]
    if contact_parts:
        draw_wrapped("  |  ".join(str(p) for p in contact_parts),
                     fontsize=9, color=MUTED, line_height=13)

    # Profile links — clickable, one line
    links = []
    for label, key in (("Portfolio", "website"), ("LinkedIn", "linkedin"), ("GitHub", "github")):
        url = str(personal.get(key) or "").strip()
        if url:
            full_url = url if url.startswith("http") else f"https://{url}"
            links.append((f"{label}: {url}", full_url))
    if links:
        x = MARGIN
        ensure_space(13)
        for i, (label_text, uri) in enumerate(links):
            display = label_text + ("   " if i < len(links) - 1 else "")
            text_w = fitz.get_text_length(display, fontname="helv", fontsize=8.5)
            if x + text_w > PAGE_W - MARGIN:  # wrap link row if needed
                state["y"] += 12
                ensure_space(13)
                x = MARGIN
            state["page"].insert_text((x, state["y"]), display, fontsize=8.5,
                                      fontname="helv", color=(0.1, 0.3, 0.6))
            state["page"].insert_link({
                "kind": fitz.LINK_URI, "uri": uri,
                "from": fitz.Rect(x, state["y"] - 8.5, x + text_w, state["y"] + 2),
            })
            x += text_w
        state["y"] += 13

    state["y"] += 4
    shape = state["page"].new_shape()
    shape.draw_line(fitz.Point(MARGIN, state["y"]), fitz.Point(PAGE_W - MARGIN, state["y"]))
    shape.finish(color=(0.8, 0.8, 0.8), width=1)
    shape.commit()
    state["y"] += 6

    # ── 2. Summary ─────────────────────────────────────────────────────
    summary = content_json.get("summary", "")
    if summary:
        section_header("Summary")
        draw_wrapped(summary)

    # ── 3. Skills (categorized when available) ─────────────────────────
    skills = content_json.get("skills", [])
    skills_categories = content_json.get("skills_categories") or {}
    if skills_categories or skills:
        section_header("Skills")
        if isinstance(skills_categories, dict) and skills_categories:
            for category, items in skills_categories.items():
                if isinstance(items, list) and items:
                    draw_wrapped(f"{category}: {', '.join(str(i) for i in items)}",
                                 fontsize=9, line_height=12.5)
        elif isinstance(skills, dict):
            for category, items in skills.items():
                draw_wrapped(f"{category}: {', '.join(str(i) for i in items)}",
                             fontsize=9, line_height=12.5)
        elif isinstance(skills, list) and skills:
            draw_wrapped(", ".join(str(s) for s in skills))

    # ── 4. Experience ──────────────────────────────────────────────────
    experience = content_json.get("experience", [])
    if experience:
        section_header("Experience")
        for exp in experience:
            if not isinstance(exp, dict):
                continue
            role = first_of(exp, "role", "title")
            comp = first_of(exp, "company", "organization")
            dates = first_of(exp, "dates", "period", "duration", "year")
            header = " — ".join(p for p in (role, comp) if p)
            if dates:
                header += f"  ({dates})"
            ensure_space(16)
            draw_wrapped(header, fontname="hebo", line_height=14)
            desc = exp.get("description") or exp.get("bullets") or ""
            if desc:
                draw_bullets(desc)
            state["y"] += 4

    # ── 5. Projects ────────────────────────────────────────────────────
    projects = content_json.get("projects", [])
    if projects:
        section_header("Projects")
        for proj in projects:
            if not isinstance(proj, dict):
                continue
            title = first_of(proj, "title", "name")
            tech = first_of(proj, "tech", "stack", "technologies")
            header = title + (f"  [{tech}]" if tech else "")
            ensure_space(16)
            draw_wrapped(header, fontname="hebo", line_height=14)
            desc = proj.get("description") or proj.get("bullets") or ""
            if desc:
                draw_bullets(desc)
            state["y"] += 4

    # ── 6. Education ───────────────────────────────────────────────────
    education = content_json.get("education", [])
    if education:
        section_header("Education")
        for edu in education:
            if not isinstance(edu, dict):
                continue
            inst = first_of(edu, "institution", "school", "university")
            deg = first_of(edu, "degree", "course")
            dates = first_of(edu, "dates", "year", "years", "period")
            score = first_of(edu, "gpa", "cgpa", "score", "percentage")
            line = " — ".join(p for p in (deg, inst) if p)
            if dates:
                line += f"  ({dates})"
            draw_wrapped(line, fontname="hebo", line_height=14)
            if score:
                score_str = score if any(c.isalpha() for c in score) else f"Score: {score}"
                draw_wrapped(score_str, x=MARGIN + 12, fontsize=9, line_height=12)
            state["y"] += 2

    # ── 7. Extra sections: patents, achievements, certifications, awards ─
    extra_sections = [
        ("Patents", content_json.get("patents")),
        ("Certifications", content_json.get("certifications")),
        ("Achievements & Recognition", content_json.get("achievements")),
    ]
    # 'awards' historically duplicates patents+achievements — only render it
    # when the dedicated keys are absent.
    if not content_json.get("patents") and not content_json.get("achievements"):
        extra_sections.append(("Awards & Recognition", content_json.get("awards")))

    for title, items in extra_sections:
        if isinstance(items, list) and any(str(i).strip() for i in items):
            section_header(title)
            draw_bullets([str(i) for i in items if str(i).strip()])

    # Custom sections: [{"title": ..., "items": [...]}]
    for custom in content_json.get("custom_sections") or []:
        if isinstance(custom, dict) and custom.get("items"):
            section_header(str(custom.get("title", "Additional")))
            draw_bullets([str(i) for i in custom["items"]])

    return doc.write()
