import os
import re
import sys
import jinja2
import logging
import subprocess
import tempfile
from typing import Dict, Any

logger = logging.getLogger("nextup.latex_renderer")

# Set up jinja2 environment with alternate delimiters to avoid conflict with LaTeX curly braces
latex_jinja_env = jinja2.Environment(
    block_start_string=r'\block{',
    block_end_string='}',
    variable_start_string=r'\var{',
    variable_end_string='}',
    comment_start_string=r'\comment{',
    comment_end_string='}',
    trim_blocks=True,
    autoescape=False,
    loader=jinja2.FileSystemLoader(os.path.join(os.path.dirname(os.path.dirname(os.path.dirname(__file__))), "storage", "latex_templates"))
)

def escape_latex(val: Any) -> str:
    """Escapes special LaTeX characters to avoid compilation failures."""
    if val is None:
        return ""
    if not isinstance(val, str):
        return str(val)
        
    # Map of special LaTeX characters to escaped strings
    conv = {
        '&': r'\&',
        '%': r'\%',
        '$': r'\$',
        '#': r'\#',
        '_': r'\_',
        '{': r'\{',
        '}': r'\}',
        '~': r'\textasciitilde{}',
        '^': r'\textasciicircum{}',
        '\\': r'\textbackslash{}',
    }
    
    regex = re.compile('|'.join(re.escape(str(key)) for key in sorted(conv.keys(), key=len, reverse=True)))
    return regex.sub(lambda match: conv[match.group()], val)

# Register filter
latex_jinja_env.filters['e_tex'] = escape_latex

def render_resume_to_pdf(template_name: str, content_json: dict) -> bytes:
    """
    Renders structured resume JSON into a LaTeX template and compiles to PDF.
    If pdflatex is not installed on the system, falls back to a clean PyMuPDF drawing.
    """
    template_file = f"{template_name.lower()}.tex.j2"
    
    # 1. Escape LaTeX characters recursively in content_json
    escaped_content = _escape_dict_recursive(content_json)
    
    try:
        template = latex_jinja_env.get_template(template_file)
        rendered_tex = template.render(**escaped_content)
    except Exception as e:
        logger.error(f"Failed to render LaTeX template {template_name}: {e}")
        # If template loading fails, fall back to PyMuPDF directly
        return _render_fallback_pdf(content_json)

    # 2. Check if pdflatex is available
    has_latex = False
    try:
        # Check pdflatex version
        result = subprocess.run(["pdflatex", "-version"], stdout=subprocess.PIPE, stderr=subprocess.PIPE, check=False)
        if result.returncode == 0:
            has_latex = True
    except Exception:
        pass

    if not has_latex:
        logger.warning("pdflatex compiler not found. Falling back to PyMuPDF rendering.")
        return _render_fallback_pdf(content_json)

    # 3. Compile LaTeX in a temp directory
    with tempfile.TemporaryDirectory() as temp_dir:
        tex_path = os.path.join(temp_dir, "resume.tex")
        with open(tex_path, "w", encoding="utf-8") as f:
            f.write(rendered_tex)

        try:
            # Run pdflatex twice for table alignments/page numbers
            for _ in range(2):
                result = subprocess.run(
                    ["pdflatex", "-interaction=nonstopmode", "-halt-on-error", "resume.tex"],
                    cwd=temp_dir,
                    stdout=subprocess.PIPE,
                    stderr=subprocess.PIPE,
                    timeout=15
                )
                if result.returncode != 0:
                    stderr_out = result.stderr.decode("utf-8", errors="ignore")
                    stdout_out = result.stdout.decode("utf-8", errors="ignore")
                    logger.error(f"LaTeX compile error output:\n{stdout_out}\n{stderr_out}")
                    raise RuntimeError("LaTeX compilation failed.")
            
            pdf_path = os.path.join(temp_dir, "resume.pdf")
            if os.path.exists(pdf_path):
                with open(pdf_path, "rb") as f:
                    return f.read()
            else:
                raise FileNotFoundError("resume.pdf was not generated by pdflatex.")
                
        except Exception as compile_err:
            logger.error(f"pdflatex compilation failed: {compile_err}. Falling back to PyMuPDF.")
            return _render_fallback_pdf(content_json)

def _escape_dict_recursive(data: Any) -> Any:
    if isinstance(data, dict):
        return {k: _escape_dict_recursive(v) for k, v in data.items()}
    elif isinstance(data, list):
        return [_escape_dict_recursive(v) for v in data]
    elif isinstance(data, str):
        return escape_latex(data)
    else:
        return data

def _render_fallback_pdf(content_json: dict) -> bytes:
    """Professional PyMuPDF renderer (the production path — no TeX installed).

    Layout mirrors the classic single-column LaTeX resume: centered name and
    contact header, uppercase section titles over full-width rules, bold entry
    headers with right-aligned dates/tech, and hanging-indent bullets. Every
    section of the resume JSON is rendered with real word-wrapping and
    automatic page breaks.
    """
    import fitz
    logger.info("Generating resume PDF using PyMuPDF renderer.")

    PAGE_W, PAGE_H = 595, 842  # A4
    MARGIN = 46
    BOTTOM = PAGE_H - 46
    CONTENT_W = PAGE_W - 2 * MARGIN

    INK = (0.08, 0.08, 0.08)
    BODY = (0.15, 0.15, 0.15)
    MUTED = (0.38, 0.38, 0.38)
    ACCENT = (0.15, 0.15, 0.35)
    LINK_BLUE = (0.05, 0.25, 0.55)

    doc = fitz.open()
    state = {"page": doc.new_page(width=PAGE_W, height=PAGE_H), "y": MARGIN}

    def ensure_space(needed: float):
        if state["y"] + needed > BOTTOM:
            state["page"] = doc.new_page(width=PAGE_W, height=PAGE_H)
            state["y"] = MARGIN

    def text_w(s: str, fontname: str, fontsize: float) -> float:
        return fitz.get_text_length(str(s), fontname=fontname, fontsize=fontsize)

    def wrap(text_val: str, fontsize: float, fontname: str, width: float):
        """Greedy word-wrap using real glyph metrics."""
        # Base-14 Helvetica lacks em/en-dash glyphs (they render as '·')
        text_val = str(text_val).replace("—", "-").replace("–", "-")
        words = text_val.split()
        lines, current = [], ""
        for word in words:
            candidate = f"{current} {word}".strip()
            if text_w(candidate, fontname, fontsize) <= width:
                current = candidate
            else:
                if current:
                    lines.append(current)
                current = word
        if current:
            lines.append(current)
        return lines or [""]

    def draw_wrapped(text_val: str, *, x: float = MARGIN, fontsize: float = 9.3,
                     fontname: str = "helv", color=BODY, width: float = None,
                     line_height: float = None, link_uri: str = None):
        width = width or (PAGE_W - MARGIN - x)
        line_height = line_height or (fontsize + 2.6)
        for line in wrap(text_val, fontsize, fontname, width):
            ensure_space(line_height)
            state["page"].insert_text((x, state["y"]), line, fontsize=fontsize,
                                      fontname=fontname, color=color)
            if link_uri:
                lw = text_w(line, fontname, fontsize)
                state["page"].insert_link({
                    "kind": fitz.LINK_URI, "uri": link_uri,
                    "from": fitz.Rect(x, state["y"] - fontsize, x + lw, state["y"] + 2),
                })
            state["y"] += line_height

    def draw_centered(text_val: str, *, fontsize: float, fontname: str = "helv",
                      color=BODY, line_height: float = None):
        line_height = line_height or (fontsize + 3)
        for line in wrap(text_val, fontsize, fontname, CONTENT_W):
            ensure_space(line_height)
            lw = text_w(line, fontname, fontsize)
            state["page"].insert_text(((PAGE_W - lw) / 2, state["y"]), line,
                                      fontsize=fontsize, fontname=fontname, color=color)
            state["y"] += line_height

    def draw_row(left: str, right: str = "", *, left_font: str = "hebo",
                 left_size: float = 10, right_font: str = "helv",
                 right_size: float = 8.8, right_color=MUTED, gap_after: float = 2):
        """Entry header: bold left text with right-aligned muted text (dates,
        tech stack) on the same line — the signature look of LaTeX resumes."""
        ensure_space(left_size + 4)
        right = str(right or "").replace("—", "-").replace("–", "-").strip()
        rw = text_w(right, right_font, right_size) if right else 0
        left_width = CONTENT_W - rw - (10 if right else 0)
        lines = wrap(left, left_size, left_font, left_width)
        state["page"].insert_text((MARGIN, state["y"]), lines[0],
                                  fontsize=left_size, fontname=left_font, color=INK)
        if right:
            state["page"].insert_text((PAGE_W - MARGIN - rw, state["y"]), right,
                                      fontsize=right_size, fontname=right_font,
                                      color=right_color)
        state["y"] += left_size + 2.5
        for extra in lines[1:]:
            ensure_space(left_size + 3)
            state["page"].insert_text((MARGIN, state["y"]), extra,
                                      fontsize=left_size, fontname=left_font, color=INK)
            state["y"] += left_size + 2.5
        state["y"] += gap_after

    def split_bullets(desc):
        """Normalize a description into logical bullets.

        PDF-parsed resumes carry the ORIGINAL line wrapping: a newline is
        usually mid-sentence, not a new bullet. A new bullet starts only at a
        bullet marker (•, -, *, ▪); marker-less lines are continuations of the
        previous bullet. Inline '•' separators (the AI emits single-line
        '• a • b' strings) also split.
        """
        if isinstance(desc, list):
            raw = [str(b) for b in desc]
        else:
            bullets = []
            for line in str(desc).split("\n"):
                stripped = line.strip()
                if not stripped:
                    continue
                if stripped[0] in "•-*▪·" or not bullets:
                    bullets.append(stripped.lstrip("•-*▪·").strip())
                else:
                    bullets[-1] += " " + stripped
            raw = bullets
        final = []
        for b in raw:
            parts = [p.strip() for p in re.split(r"\s*•\s*", b) if p.strip()]
            final.extend(parts if parts else [b.strip()])
        return [b for b in final if b]

    def draw_bullets(desc, indent: float = 10):
        """Hanging-indent bullets: wrapped lines align under the text, not
        under the bullet marker."""
        bullet_x = MARGIN + indent
        body_x = bullet_x + 9
        fontsize, line_height = 9.2, 11.8
        for b_clean in split_bullets(desc):
            first = True
            for line in wrap(b_clean, fontsize, "helv", PAGE_W - MARGIN - body_x):
                ensure_space(line_height)
                if first:
                    # A drawn disc beats the font's bullet glyph (WinAnsi
                    # Helvetica renders '•' as a faint mid-dot).
                    shape = state["page"].new_shape()
                    shape.draw_circle(
                        fitz.Point(bullet_x + 1.4, state["y"] - fontsize * 0.32), 1.15)
                    shape.finish(color=BODY, fill=BODY)
                    shape.commit()
                    first = False
                state["page"].insert_text((body_x, state["y"]), line,
                                          fontsize=fontsize, fontname="helv",
                                          color=BODY)
                state["y"] += line_height
            state["y"] += 0.8

    def section_header(title: str):
        ensure_space(30)
        state["y"] += 9
        state["page"].insert_text((MARGIN, state["y"]), title.upper(), fontsize=10.5,
                                  fontname="hebo", color=ACCENT)
        state["y"] += 4.5
        shape = state["page"].new_shape()
        shape.draw_line(fitz.Point(MARGIN, state["y"]),
                        fitz.Point(PAGE_W - MARGIN, state["y"]))
        shape.finish(color=(0.55, 0.55, 0.62), width=0.8)
        shape.commit()
        state["y"] += 11

    def first_of(d: dict, *keys) -> str:
        for k in keys:
            v = d.get(k)
            if v:
                return str(v)
        return ""

    # ── 1. Header: centered name + contact + links ─────────────────────
    personal = content_json.get("personal", {}) or {}
    name = str(personal.get("name") or "Student Resume").upper()
    ensure_space(26)
    state["y"] += 14
    nw = text_w(name, "hebo", 19)
    state["page"].insert_text(((PAGE_W - nw) / 2, state["y"]), name,
                              fontsize=19, fontname="hebo", color=INK)
    state["y"] += 15

    contact_parts = [str(p) for p in (personal.get("email"), personal.get("phone"),
                                      personal.get("location")) if p]
    if contact_parts:
        draw_centered("  |  ".join(contact_parts), fontsize=8.8, color=MUTED,
                      line_height=12)

    # Profile links — clickable, centered on one row
    links = []
    for label, key in (("Portfolio", "website"), ("LinkedIn", "linkedin"), ("GitHub", "github")):
        url = str(personal.get(key) or "").strip()
        if url:
            full_url = url if url.startswith("http") else f"https://{url}"
            links.append((label, full_url))
    if links:
        sep = "   |   "
        row_parts = [lbl for lbl, _ in links]
        row_text = sep.join(row_parts)
        total = text_w(row_text, "helv", 8.8)
        x = (PAGE_W - total) / 2
        ensure_space(12)
        for i, (lbl, uri) in enumerate(links):
            lw = text_w(lbl, "helv", 8.8)
            state["page"].insert_text((x, state["y"]), lbl, fontsize=8.8,
                                      fontname="helv", color=LINK_BLUE)
            state["page"].insert_link({
                "kind": fitz.LINK_URI, "uri": uri,
                "from": fitz.Rect(x, state["y"] - 8.8, x + lw, state["y"] + 2),
            })
            x += lw
            if i < len(links) - 1:
                state["page"].insert_text((x, state["y"]), sep, fontsize=8.8,
                                          fontname="helv", color=MUTED)
                x += text_w(sep, "helv", 8.8)
        state["y"] += 12

    state["y"] += 2

    # ── 2. Summary ─────────────────────────────────────────────────────
    summary = content_json.get("summary", "")
    if summary:
        section_header("Summary")
        draw_wrapped(str(summary), fontsize=9.3, line_height=12.2)

    # ── 3. Skills (categorized when available) ─────────────────────────
    skills = content_json.get("skills", [])
    skills_categories = content_json.get("skills_categories") or {}
    cat_source = None
    if isinstance(skills_categories, dict) and skills_categories:
        cat_source = skills_categories
    elif isinstance(skills, dict):
        cat_source = skills
    if cat_source or skills:
        section_header("Skills")
        if cat_source:
            for category, items in cat_source.items():
                if not (isinstance(items, list) and items):
                    continue
                # Bold category label, regular items — mixed fonts inline
                label = f"{category}: "
                lw = text_w(label, "hebo", 9.2)
                items_text = ", ".join(str(i) for i in items)
                lines = wrap(items_text, 9.2, "helv", CONTENT_W - lw)
                ensure_space(12)
                state["page"].insert_text((MARGIN, state["y"]), label,
                                          fontsize=9.2, fontname="hebo", color=INK)
                state["page"].insert_text((MARGIN + lw, state["y"]), lines[0],
                                          fontsize=9.2, fontname="helv", color=BODY)
                state["y"] += 11.8
                for extra in lines[1:]:
                    ensure_space(12)
                    state["page"].insert_text((MARGIN + lw, state["y"]), extra,
                                              fontsize=9.2, fontname="helv", color=BODY)
                    state["y"] += 11.8
        elif isinstance(skills, list) and skills:
            draw_wrapped(", ".join(str(s) for s in skills), fontsize=9.2,
                         line_height=12)

    # ── 4. Experience ──────────────────────────────────────────────────
    experience = content_json.get("experience", [])
    if experience:
        section_header("Experience")
        for exp in experience:
            if not isinstance(exp, dict):
                continue
            role = first_of(exp, "role", "title")
            comp = first_of(exp, "company", "organization")
            dates = first_of(exp, "dates", "period", "duration", "year")
            header = " — ".join(p for p in (role, comp) if p)
            draw_row(header, dates)
            desc = exp.get("description") or exp.get("bullets") or ""
            if desc:
                draw_bullets(desc)
            state["y"] += 3

    # ── 5. Projects ────────────────────────────────────────────────────
    projects = content_json.get("projects", [])
    if projects:
        section_header("Projects")
        for proj in projects:
            if not isinstance(proj, dict):
                continue
            title = first_of(proj, "title", "name")
            tech = first_of(proj, "tech", "stack", "technologies")
            draw_row(title, tech, right_color=ACCENT)
            desc = proj.get("description") or proj.get("bullets") or ""
            if desc:
                draw_bullets(desc)
            state["y"] += 3

    # ── 6. Education ───────────────────────────────────────────────────
    education = content_json.get("education", [])
    if education:
        section_header("Education")
        for edu in education:
            if not isinstance(edu, dict):
                continue
            inst = first_of(edu, "institution", "school", "university")
            deg = first_of(edu, "degree", "course")
            dates = first_of(edu, "dates", "year", "years", "period")
            score = first_of(edu, "gpa", "cgpa", "score", "percentage")
            line = " — ".join(p for p in (deg, inst) if p)
            score_str = ""
            if score:
                score_str = score if any(c.isalpha() for c in score) else f"Score: {score}"
            draw_row(line, dates)
            if score_str:
                draw_wrapped(score_str, x=MARGIN + 10, fontsize=9,
                             line_height=11.5, color=MUTED)
            state["y"] += 2

    # ── 7. Extra sections: patents, achievements, certifications, awards ─
    extra_sections = [
        ("Patents", content_json.get("patents")),
        ("Certifications", content_json.get("certifications")),
        ("Achievements & Recognition", content_json.get("achievements")),
    ]
    # 'awards' historically duplicates patents+achievements — only render it
    # when the dedicated keys are absent.
    if not content_json.get("patents") and not content_json.get("achievements"):
        extra_sections.append(("Awards & Recognition", content_json.get("awards")))

    for title, items in extra_sections:
        if isinstance(items, list) and any(str(i).strip() for i in items):
            section_header(title)
            draw_bullets([str(i) for i in items if str(i).strip()])

    # Custom sections: [{"title": ..., "items": [...]}]
    for custom in content_json.get("custom_sections") or []:
        if isinstance(custom, dict) and custom.get("items"):
            section_header(str(custom.get("title", "Additional")))
            draw_bullets([str(i) for i in custom["items"]])

    return doc.write()
